locale                   : "en-US"
site_theme               : "mint"
title                    : "Santanu Soe"
title_separator          : "-"
name                     : &name "Santanu Soe"
description              : "Personal academic website of Santanu Soe, PMRF and Joint PhD scholar in Mathematics at IIT Madras and The University of Melbourne."
url                      : "https://santanusoe.github.io"
baseurl                  : ""
repository               : "santanusoe/santanusoe.github.io"

author:
  avatar           : "profile.svg"
  name             : "Santanu Soe"
  pronouns         :
  bio              : 
  location         : 
  employer         : 
  uri              :
  email            :

  academia         :
  arxiv            :
  googlescholar    : "https://scholar.google.com/citations?user=1xQZCtQAAAAJ&hl=en"
  inspire-hep      :
  impactstory      :
  orcid            : "https://orcid.org/0009-0005-1392-0003"
  semantic         :
  ssrn             :
  pubmed           :
  researchgate     : "https://www.researchgate.net/profile/Santanu-Soe"
  scopus           :
  zotero           :

  bitbucket        :
  codepen          :
  dribbble         :
  github           :
  kaggle           :
  stackoverflow    :

  artstation       :
  bluesky          :
  facebook         :
  flickr           :
  foursquare       :
  goodreads        :
  google_plus      :
  keybase          :
  instagram        :
  lastfm           :
  linkedin         :
  mastodon         :
  medium           :
  pinterest        :
  soundcloud       :
  steam            :
  telegram         :
  tumblr           :
  twitter          :
  vine             :
  weibo            :
  wikipedia        :
  xing             :
  youtube          :
  zhihu            :

# Publication Category - The following the list of publication categories and their headings
publication_category:
  preprints:
    title: 'Preprints'
  manuscripts:
    title: 'Journal Articles'
  conferences:
    title: 'Conference Papers'

# Site Settings
teaser                   :
breadcrumbs              : false
words_per_minute         : 160
future                   : true
read_more                : "disabled"
talkmap_link             : false
comments:
  provider               :
  disqus:
    shortname            :
  discourse:
    server               :
  facebook:
    appid                :
    num_posts            :
    colorscheme          :
staticman:
  allowedFields          : ['name', 'email', 'url', 'message']
  branch                 : "gh-pages"
  commitMessage          : "New comment."
  filename               : comment-{@timestamp}
  format                 : "yml"
  moderation             : true
  path                   : "_data/comments/{options.slug}"
  requiredFields         : ['name', 'email', 'message']
  transforms:
    email                : "md5"
  generatedFields:
    date:
      type               : "date"
      options:
        format           : "iso8601"
atom_feed:
  hide                   : true
  path                   :

# SEO Related
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

# Social Sharing
twitter:
  username               : &twitter
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 :
og_description           :
social:
  type                   :
  name                   :
  links:

# Analytics
analytics:
  provider               : "false"
  google:
    tracking_id          :

# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - CHANGELOG
  - Capfile
  - config
  - Dockerfile
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - local
  - log
  - node_modules
  - package.json*
  - Rakefile
  - README
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      share: true
      comment: true
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true

sass:
  sass_dir: _sass
  style: compressed

permalink: /:categories/:title/
timezone: Asia/Kolkata

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from

whitelist:
  - jekyll-sitemap
  - jekyll-redirect-from

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

compress_html:
  clippings: all
  ignore:
    envs: development
